spring.application.name=member_app
#MySQL \uC5F0\uACB0
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/member_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PW}

# SQL \uB85C\uADF8
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

### \uD14C\uC774\uBE14 \uC790\uB3D9 \uC0DD\uC131 \uC804\uB7B5
# create
# update
# validate
# none
spring.jpa.hibernate.ddl-auto=update

# \uB85C\uADF8 \uCD9C\uB825
logging.level.org.hibernate.type.descriptor.sql=trace

# \uBC29\uC5B8\uC124\uC815
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect